#pragma once

enum VoiceCommand : int {
    VOICE_COMMAND_NONE = 0,
    VOICE_COMMAND_PROJECTOR_OFF,
    VOICE_COMMAND_PROJECTOR_ON,
    VOICE_COMMAND_SHOW_BRIGHTNESS,
    VOICE_COMMAND_SHOW_BATTERY,
    VOICE_COMMAND_SHOW_SPEED,
    VOICE_COMMAND_SHOW_TIME,
    VOICE_COMMAND_SHOW_CALORIES,
    VOICE_COMMAND_SHOW_DISTANCE,
    VOICE_COMMAND_SHOW_LAPS,
    VOICE_COMMAND_SHOW_PAGE_62,
    VOICE_COMMAND_SHOW_PAGE_63,
    VOICE_COMMAND_SET_BRIGHTNESS,
    VOICE_COMMAND_BRIGHTNESS_UP,
    VOICE_COMMAND_BRIGHTNESS_DOWN,
};

const char* voiceCommandName(VoiceCommand command);
