#pragma once

#ifndef ENABLE_GPS_VERBOSE_LOG
#define ENABLE_GPS_VERBOSE_LOG 0
#endif

#ifndef ENABLE_GPS_SUMMARY_LOG
#define ENABLE_GPS_SUMMARY_LOG 0
#endif

#ifndef ENABLE_TOUCH_DIAG_LOG
#define ENABLE_TOUCH_DIAG_LOG 0
#endif

#ifndef ENABLE_PMU_DIAG_LOG
#define ENABLE_PMU_DIAG_LOG 0
#endif

#ifndef ENABLE_RTC_DIAG_LOG
#define ENABLE_RTC_DIAG_LOG 0
#endif

#ifndef ENABLE_PMU_UI_LOG
#define ENABLE_PMU_UI_LOG 0
#endif

#ifndef ENABLE_RTC_UI_LOG
#define ENABLE_RTC_UI_LOG 0
#endif

#ifndef ENABLE_DISPLAY_STATE_LOG
#define ENABLE_DISPLAY_STATE_LOG 1
#endif

#ifndef ENABLE_DISPLAY_STATE_SERIAL_LOG
#define ENABLE_DISPLAY_STATE_SERIAL_LOG 1
#endif

#ifndef ENABLE_DISPLAY_BLE_LOG
#define ENABLE_DISPLAY_BLE_LOG 1
#endif

#ifndef ENABLE_SETUP_STEP_LOG
#define ENABLE_SETUP_STEP_LOG 1
#endif

#ifndef ENABLE_SYSTEM_SUMMARY_LOG
#define ENABLE_SYSTEM_SUMMARY_LOG 1
#endif

#ifndef SYSTEM_SUMMARY_INTERVAL_MS
#define SYSTEM_SUMMARY_INTERVAL_MS 2000
#endif

#ifndef ENABLE_SYSTEM_RESOURCE_LOG
#define ENABLE_SYSTEM_RESOURCE_LOG 1
#endif

#ifndef ENABLE_PERIODIC_RESOURCE_LOG
#define ENABLE_PERIODIC_RESOURCE_LOG 0
#endif

#ifndef ENABLE_RESOURCE_BASELINE_AUDIT
#define ENABLE_RESOURCE_BASELINE_AUDIT 1
#endif

#ifndef ENABLE_IMU_SPEED_DEBUG_LOG
#define ENABLE_IMU_SPEED_DEBUG_LOG 0
#endif
